BEGIN TRANSACTION;
CREATE TABLE `SUITE` (
	`SuiteID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`SuiteType`	TEXT NOT NULL UNIQUE
);
CREATE TABLE `STUDENT_PASSWORD` (
	`PasswordID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`StudentID`	INTEGER NOT NULL UNIQUE,
	`SecurityQuestionID`	INTEGER NOT NULL,
	`Password`	TEXT NOT NULL,
	`SecurityAnswer`	TEXT,
	FOREIGN KEY(`StudentID`) REFERENCES STUDENT(StudentID),
	FOREIGN KEY(`SecurityQuestionID`) REFERENCES SECURITY_QUESTION(SecurityQuestionID)
);
CREATE TABLE "STUDENT" (
	`StudentID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`RoomID`	INTEGER NOT NULL,
	`FirstName`	NUMERIC NOT NULL,
	`LastName`	TEXT NOT NULL,
	`Phone`	TEXT NOT NULL,
	`Address`	TEXT NOT NULL,
	`PersonalEMail`	TEXT,
	`SchoolEMail`	TEXT NOT NULL,
	FOREIGN KEY(`RoomID`) REFERENCES ROOM ( RoomID )
);
CREATE TABLE `STAFF_PASSWORD` (
	`PasswordID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`StaffID`	INTEGER NOT NULL,
	`Password`	TEXT NOT NULL,
	FOREIGN KEY(`StaffID`) REFERENCES STAFF(StaffID)
);
CREATE TABLE `STAFF` (
	`StaffID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`RoleID`	INTEGER NOT NULL,
	`SecurityQuestionID`	INTEGER NOT NULL,
	FOREIGN KEY(`RoleID`) REFERENCES ROLE(RoleID),
	FOREIGN KEY(`SecurityQuestionID`) REFERENCES SECURITY_QUESTION(SecurityQuestionID)
);
CREATE TABLE `SECURITY_QUESTION` (
	`SecurityQuestionID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Question`	TEXT NOT NULL UNIQUE
);
CREATE TABLE `ROOM_SELECTION_FORM` (
	`RoomSelectionID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`RoomGroupID`	INTEGER,
	`StudentID`	INTEGER NOT NULL,
	`ProxyOption`	INTEGER,
	`ProxySignature`	TEXT,
	`ProxyDate`	TEXT,
	`SuiteRoom1`	TEXT NOT NULL,
	`Rommate1`	TEXT,
	`SuiteRoom2`	TEXT,
	`Roommate2`	TEXT,
	`Suite`	TEXT,
	`Representative`	TEXT,
	`CurrentSemester`	TEXT NOT NULL,
	`AssisgmentFollowingSemester`	TEXT NOT NULL,
	`Notes`	TEXT,
	`Signature`	TEXT NOT NULL,
	`SignatureDate`	INTEGER NOT NULL
);
CREATE TABLE `ROOM_GROUP` (
	`RoomGroupID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`RoomID`	INTEGER NOT NULL,
	`StudentName`	TEXT NOT NULL,
	`Signature`	TEXT NOT NULL,
	FOREIGN KEY(`RoomID`) REFERENCES ROOM(RoomID)
);
CREATE TABLE "ROOM" (
	`RoomID`	INTEGER NOT NULL UNIQUE,
	`BuildingID`	INTEGER NOT NULL,
	`SuiteID`	INTEGER NOT NULL,
	`RoomNumber`	TEXT NOT NULL,
	`RoomType`	TEXT NOT NULL,
	`Floor`	INTEGER NOT NULL,
	PRIMARY KEY(RoomID,RoomNumber),
	FOREIGN KEY(`BuildingID`) REFERENCES Building ( BuildingID ),
	FOREIGN KEY(`SuiteID`) REFERENCES Suite ( SuiteID )
);
CREATE TABLE `ROLE` (
	`RoleID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Description`	TEXT NOT NULL UNIQUE
);
CREATE TABLE `RESIDENCE_DIRECTOR` (
	`ResidenceDirectorID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`StaffID`	INTEGER NOT NULL,
	`FirstName`	TEXT NOT NULL,
	`LastName`	TEXT NOT NULL,
	`Phone`	TEXT NOT NULL,
	`Email`	TEXT NOT NULL,
	`Address`	TEXT NOT NULL,
	`Password`	TEXT NOT NULL,
	FOREIGN KEY(`StaffID`) REFERENCES STAFF(StaffID)
);
CREATE TABLE "RESIDENCE_ASSISTANT" (
	`ResidentAssistatnID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`StaffID`	INTEGER NOT NULL,
	`FirstName`	TEXT NOT NULL,
	`LastName`	TEXT NOT NULL,
	`Phone`	TEXT NOT NULL,
	`Email`	TEXT NOT NULL,
	`Address`	TEXT NOT NULL,
	`Password`	TEXT NOT NULL
);
CREATE TABLE "HOUSING_APPLICATION" (
	`HousingApplicationID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`StudentID`	INTEGER NOT NULL,
	`HousingRequestDate`	TEXT NOT NULL,
	`EmergencyContact`	TEXT NOT NULL,
	`RoommatePreference`	TEXT,
	`Smoke`	INTEGER,
	`EarlyRiser`	INTEGER,
	`SleepEarlyAtNight`	INTEGER,
	`StudyQuietlyLate`	INTEGER,
	`ConsiderToBeAPerson`	TEXT,
	`MedicalConcerns`	TEXT,
	`StudentSignatureDate`	TEXT NOT NULL,
	`StudentSignature`	TEXT NOT NULL,
	`ReleaseInfoToRommate`	INTEGER,
	`GuardianSignature`	TEXT,
	`GuardianSignatureDate`	TEXT,
	`SADate`	TEXT NOT NULL,
	`Cashier`	TEXT NOT NULL,
	`BLODate`	TEXT NOT NULL
);
CREATE TABLE `BUILDING` (
	`BuildingID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE,
	`NumberOfFloors`	INTEGER NOT NULL
);
COMMIT;
